### ISSUE TITLE
bot.Profile.Id Returns Zero

### ISSUE THREAD

**Issue by burakgarci** [calico-crusade/palringo-api-std#1]
https://github.com/calico-crusade/palringo-api-std/blob/a0d4808cbfc6bd039ec3c89b91bacb3eb07d58d1/PalApi/PalBot.cs#L32

**Comment by calico-crusade** [comment]
I cannot recreate this issue. It seems to be working fine for me.
![screenshot_16](https://user-images.githubusercontent.com/31460039/41006514-dbf6810a-68ef-11e8-887a-f31de3e79c20.png)
![screenshot_17](https://user-images.githubusercontent.com/31460039/41006515-dc230c3e-68ef-11e8-855e-3b3176d38345.png)
![screenshot_18](https://user-images.githubusercontent.com/31460039/41006574-14ac1c94-68f0-11e8-98e6-cc3d8162647e.png)
