### ISSUE TITLE
Default does not give any cmd

### ISSUE THREAD

**Issue by ateeqarshad** [calico-crusade/palringo-api-std#4]
```
[Default, Command("find")]
        public async void OnDefault(IPalBot bot, Message msg, string cmd)
        {
            String a = Default.;
            Console.WriteLine(a);
        

            var gifResponse = a;

            gifRequest(a);
            await bot.Reply(msg, gifToOutput);
            gifToOutput = "";
        }
```

CMD does not return anything. I have told Alec about this issue on Palringo.

**Comment by calico-crusade** [comment]
This is by design. Default will only be triggered if the message only matches the namespace. I don't believe this warrants attention as it breaks the flow of how the plugins work and could lead to unexpected behavior for other users.
