### ISSUE TITLE
Two or more commands being triggered

### ISSUE THREAD

**Issue by dawalters1** [calico-crusade/palringo-api-std#5]
Currently using [LCommand()] so not sure if this affects [Command()]

if you have lets say a command that uses trigger "a", another that uses "auto" and one more that uses "autoplay" and then use "!whatever autoplay"

instead of triggering the command with the longest match which would be autoplay, it will trigger all 3 of the commands

http://prntscr.com/kjlcmf

**Comment by calico-crusade** [comment]
This is a duplicate of #6, see the resolution there.
