### ISSUE TITLE
Multiple abbreviations of a command call base commands.

### ISSUE THREAD

**Issue by skysb1** [calico-crusade/palringo-api-std#6]
Supposing we have "!bot scores ID" and "!bot sc ID", if we set up two command methods for it, "!bot sc ID" is called twice (supposing it uses a startswith or regular expression) where in the score time, the cmd received is "ores ID".

It would be great if the API support command abbreviations. (Either by removing the startswith and making it equal to, or allow multiple command definitions in the same property, if possible).

Cheers

**Comment by calico-crusade** [comment]
I have rectified this issue in the latest-rewrite of the API it can be found at [BotsDotNet](http://github.com/calico-crusade/botsdotnet). Please use that library to work with override-able plugins.
